(griffin.c) Fix build when freetype2 support is enabled
This commit fixes build issues for frontends that wish to use freetype2
or that do not want to use the built-in bitmap font:

* Having HAVE_FREETYPE without DONT_HAVE_BITMAPFONT makes griffin.c
  include both freetype.c and bitmapfont.c resulting in a redefinition
  of 'struct font_renderer' (freetype.c:25 and bitmapfont.c:24).

* Having both HAVE_FREETYPE and DONT_HAVE_BITMAPFONT resulted in linkage
  problems because griffin.c does not include fonts.c in this case and
  thus font_renderer_create_default() implementation is missing. If
  fonts.c is included, the linker complains about undefined reference to
  bitmap_font_renderer in fonts.c:27.