Squashed 'deps/SPIRV-Cross/' changes from f3a75d1d4b..eb9b273298
eb9b273298 Merge pull request #2094 from LibretroAdmin/main
5029e30f0a (spirv_glsl.cpp) Fix error: no matching function for call to 'max(uint32_t&, unsigned int)'

git-subtree-dir: deps/SPIRV-Cross
git-subtree-split: eb9b2732982b8eea3395216be825a74dd84fe4be